name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a2/cr'
        name: 'cr'
        version: '0.7.0-a2'

    - uses: supplypike/setup-bin@v3
      with:
        uri: 'https://github.com/calcit-lang/calcit/releases/download/0.7.0-a2/caps'
        name: 'caps'
        version: '0.7.0-a2'

    - name: "load deps"
      run: caps --ci && yarn

    - name: "test js"
      run: >
        cr -1 --emit-js --init-fn=respo.test.main/main!
        && node test.mjs

    - name: "build js"
      run: >
        cr --once --emit-js
        && yarn vite build --base=./

    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v2.0.0
      env:
        DEPLOY_KEY: ${{secrets.rsync_private_key}}
      with:
        flags: '-avzr --progress'
        options: ''
        ssh_options: ''
        src: 'dist/*'
        dest: 'rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}'

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
